# Generated by Django 3.1.7 on 2021-03-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0002_auto_20210323_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='thumb',
            new_name='image',
        ),
        migrations.AddField(
            model_name='services',
            name='subservices',
            field=models.TextField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sub_services',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.services'),
        ),
    ]
