# Generated by Django 3.1.7 on 2021-03-29 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0003_auto_20210329_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preview_images',
            old_name='images',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='preview_images',
            name='title',
        ),
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
        migrations.RemoveField(
            model_name='services',
            name='subservices',
        ),
        migrations.AddField(
            model_name='preview_images',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/services'),
        ),
        migrations.AddField(
            model_name='sub_services',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='constructionapp.services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_services',
            name='title',
            field=models.TextField(default=' ', max_length=254),
        ),
    ]
