# Generated by Django 3.1.7 on 2021-03-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0004_auto_20210329_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
