# Generated by Django 3.1.7 on 2021-03-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0005_auto_20210330_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='sliderhome',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sub_services',
            name='title',
            field=models.TextField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
