# Generated by Django 3.1.7 on 2021-04-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0007_auto_20210330_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='media/subservices')),
            ],
        ),
        migrations.DeleteModel(
            name='Sub_Services',
        ),
        migrations.AddField(
            model_name='services',
            name='servicetype',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='constructionapp.servicetype'),
            preserve_default=False,
        ),
    ]
