# Generated by Django 3.1.7 on 2021-04-19 14:21

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0008_auto_20210418_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/clients')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media/features')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='about',
            old_name='heading',
            new_name='longdesc',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='shortdesc',
        ),
        migrations.RenameField(
            model_name='preview_images',
            old_name='image',
            new_name='shortthumb',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='aboutdesc',
            new_name='longdesc',
        ),
        migrations.AddField(
            model_name='about',
            name='long_thumb',
            field=models.ImageField(default=2, upload_to='media/about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='short_thumb',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preview_images',
            name='longthumb',
            field=models.ImageField(blank=True, null=True, upload_to='media/services'),
        ),
        migrations.CreateModel(
            name='PortFolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/portfolio')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.projectstatus'),
        ),
    ]
