# Generated by Django 3.1.7 on 2021-04-20 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0009_auto_20210419_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubServiceslist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.services')),
            ],
        ),
    ]
