# Generated by Django 3.1.7 on 2021-04-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0011_auto_20210420_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subserviceslist',
            old_name='service_title',
            new_name='servicetitle',
        ),
    ]
