# Generated by Django 3.1.7 on 2021-04-25 06:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0012_auto_20210424_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=254, null=True)),
                ('emailaddress', models.EmailField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=254, null=True)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subserviceslist',
            name='servicetitle',
            field=models.CharField(max_length=50),
        ),
    ]
