# Generated by Django 3.1.7 on 2021-04-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0013_auto_20210425_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='clientname',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
