# Generated by Django 3.1.7 on 2021-04-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0014_clients_clientname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='quote',
            field=models.TextField(max_length=100),
        ),
    ]
