# Generated by Django 3.1.7 on 2021-04-26 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0015_auto_20210425_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview_images',
            name='shortthumb',
        ),
        migrations.AddField(
            model_name='services',
            name='shortthumb',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/services'),
            preserve_default=False,
        ),
    ]
