# Generated by Django 3.1.7 on 2021-04-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0016_auto_20210426_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('On Going', 'On Going'), ('Completed', 'Completed'), ('Proposed', 'Proposed')], max_length=200),
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
