# Generated by Django 3.2.4 on 2021-07-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0017_auto_20210426_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
