# Generated by Django 3.2.4 on 2021-07-03 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0018_alter_portfolio_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='status',
        ),
        migrations.CreateModel(
            name='PortfolioStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructionapp.portfolio')),
            ],
        ),
    ]
