# Generated by Django 3.2.4 on 2021-07-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0020_auto_20210703_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliostatus',
            old_name='status',
            new_name='title',
        ),
    ]
