# Generated by Django 3.2.4 on 2021-07-03 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0021_rename_status_portfoliostatus_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliostatus',
            old_name='title',
            new_name='status_title',
        ),
    ]
