# Generated by Django 3.2.4 on 2021-07-04 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0022_rename_title_portfoliostatus_status_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(choices=[('Proposed', 'Proposed'), ('Ón Going', 'Ón Going'), ('Çompleted', 'Çompleted')], default='Proposed', max_length=256),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='constructionapp.portfolio'),
        ),
    ]
