# Generated by Django 3.2.4 on 2021-08-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0024_auto_20210802_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview_images',
            name='shortthumb',
        ),
        migrations.AddField(
            model_name='services',
            name='shortthumb',
            field=models.ImageField(default=1, upload_to='media/services'),
            preserve_default=False,
        ),
    ]
