# Generated by Django 3.2.4 on 2021-08-13 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0025_auto_20210802_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subserviceslist',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='constructionapp.services'),
        ),
    ]
